name:                rbtree
version:             0.1.0.0
github:              "githubuser/rbtree"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/rbtree#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  rbtree-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rbtree
    - criterion >= 1.4.1.0
    - deepseq >= 1.4.3.0

tests:
  rbtree-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rbtree
    - tasty >= 1.1.0.2
    - tasty-hunit >= 0.10.0.1
    - smallcheck >= 1.1.5
    - tasty-smallcheck >= 0.8.1
    - tasty-quickcheck >= 0.10
